export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAILURE = 'FETCH_PHONES_FAILURE';

export const FETCH_PHONES_PAGE_START = 'FETCH_PHONES_PAGE_START';
export const FETCH_PHONES_PAGE_SUCCESS = 'FETCH_PHONES_PAGE_SUCCESS';
export const FETCH_PHONES_PAGE_FAILURE = 'FETCH_PHONES_PAGE_FAILURE';


export const LOAD_MORE_PHONES_START = 'LOAD_MORE_PHONES_START';
export const LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS';
export const LOAD_MORE_PHONES_FAILURE = 'LOAD_MORE_PHONES_FAILURE';
